package com.arefdev.base.enums

import android.os.Build

/**
 * Updated on 21/09/2023
 *
 * @author <a href="https://github.com/arefbhrn">Aref Bahreini</a>
 */
enum class SDK(val value: Int) {
    BASE(SDK_CODES.BASE),
    BASE_1_1(SDK_CODES.BASE_1_1),
    CUPCAKE(SDK_CODES.CUPCAKE),
    DONUT(SDK_CODES.DONUT),
    ECLAIR(SDK_CODES.ECLAIR),
    ECLAIR_0_1(SDK_CODES.ECLAIR_0_1),
    ECLAIR_MR1(SDK_CODES.ECLAIR_MR1),
    FROYO(SDK_CODES.FROYO),
    GINGERBREAD(SDK_CODES.GINGERBREAD),
    GINGERBREAD_MR1(SDK_CODES.GINGERBREAD_MR1),
    HONEYCOMB(SDK_CODES.HONEYCOMB),
    HONEYCOMB_MR1(SDK_CODES.HONEYCOMB_MR1),
    HONEYCOMB_MR2(SDK_CODES.HONEYCOMB_MR2),
    ICE_CREAM_SANDWICH(SDK_CODES.ICE_CREAM_SANDWICH),
    ICE_CREAM_SANDWICH_MR1(SDK_CODES.ICE_CREAM_SANDWICH_MR1),
    JELLY_BEAN(SDK_CODES.JELLY_BEAN),
    JELLY_BEAN_MR1(SDK_CODES.JELLY_BEAN_MR1),
    JELLY_BEAN_MR2(SDK_CODES.JELLY_BEAN_MR2),
    KITKAT(SDK_CODES.KITKAT),
    KITKAT_WATCH(SDK_CODES.KITKAT_WATCH),
    LOLLIPOP(SDK_CODES.LOLLIPOP),
    LOLLIPOP_MR1(SDK_CODES.LOLLIPOP_MR1),
    M(SDK_CODES.M),
    N(SDK_CODES.N),
    N_MR1(SDK_CODES.N_MR1),
    O(SDK_CODES.O),
    O_MR1(SDK_CODES.O_MR1),
    P(SDK_CODES.P),
    Q(SDK_CODES.Q),
    R(SDK_CODES.R),
    S(SDK_CODES.S),
    S_V2(SDK_CODES.S_V2),
    TIRAMISU(SDK_CODES.TIRAMISU),
    UPSIDE_DOWN_CAKE(SDK_CODES.UPSIDE_DOWN_CAKE),
    ;

    companion object {
        fun byValue(sdk: Int): SDK? {
            return entries.find { it.value == sdk }
        }
    }
}

typealias SDK_CODES = Build.VERSION_CODES